<?php

use Illuminate\Database\Seeder;

class DaerahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinsi = [
            ['id' => 21, 'provinsi' => 'Nanggroe Aceh Darussalam (NAD)'],
            ['id' => 32, 'provinsi' => 'Sumatera Barat'],
            ['id' => 23, 'provinsi' => 'Nusa Tenggara Timur (NTT)'],
            ['id' => 19, 'provinsi' => 'Maluku'],
            ['id' => 34, 'provinsi' => 'Sumatera Utara'],
            ['id' => 24, 'provinsi' => 'Papua'],
            ['id' => 1, 'provinsi' => 'Bali'],
            ['id' => 13, 'provinsi' => 'Kalimantan Selatan'],
            ['id' => 15, 'provinsi' => 'Kalimantan Timur'],
            ['id' => 18, 'provinsi' => 'Lampung'],
            ['id' => 9, 'provinsi' => 'Jawa Barat'],
            ['id' => 29, 'provinsi' => 'Sulawesi Tengah'],
            ['id' => 2, 'provinsi' => 'Bangka Belitung'],
            ['id' => 11, 'provinsi' => 'Jawa Timur'],
            ['id' => 10, 'provinsi' => 'Jawa Tengah'],
            ['id' => 28, 'provinsi' => 'Sulawesi Selatan'],
            ['id' => 5, 'provinsi' => 'DI Yogyakarta'],
            ['id' => 33, 'provinsi' => 'Sumatera Selatan'],
            ['id' => 14, 'provinsi' => 'Kalimantan Tengah'],
            ['id' => 17, 'provinsi' => 'Kepulauan Riau'],
            ['id' => 8, 'provinsi' => 'Jambi'],
            ['id' => 30, 'provinsi' => 'Sulawesi Tenggara'],
            ['id' => 26, 'provinsi' => 'Riau'],
            ['id' => 12, 'provinsi' => 'Kalimantan Barat'],
            ['id' => 4, 'provinsi' => 'Bengkulu'],
            ['id' => 22, 'provinsi' => 'Nusa Tenggara Barat (NTB)'],
            ['id' => 31, 'provinsi' => 'Sulawesi Utara'],
            ['id' => 7, 'provinsi' => 'Gorontalo'],
            ['id' => 16, 'provinsi' => 'Kalimantan Utara'],
            ['id' => 3, 'provinsi' => 'Banten'],
            ['id' => 25, 'provinsi' => 'Papua Barat'],
            ['id' => 20, 'provinsi' => 'Maluku Utara'],
            ['id' => 6, 'provinsi' => 'DKI Jakarta'],
            ['id' => 27, 'provinsi' => 'Sulawesi Barat'],
        ];
        $kabupaten = [
            ['id' => 1, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '23681'],
            ['id' => 2, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Barat Daya', 'tipe' => 'Kabupaten', 'kode_pos' => '23764'],
            ['id' => 3, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Besar', 'tipe' => 'Kabupaten', 'kode_pos' => '23951'],
            ['id' => 4, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Jaya', 'tipe' => 'Kabupaten', 'kode_pos' => '23654'],
            ['id' => 5, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '23719'],
            ['id' => 6, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Singkil', 'tipe' => 'Kabupaten', 'kode_pos' => '24785'],
            ['id' => 7, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Tamiang', 'tipe' => 'Kabupaten', 'kode_pos' => '24476'],
            ['id' => 8, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '24511'],
            ['id' => 9, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Tenggara', 'tipe' => 'Kabupaten', 'kode_pos' => '24611'],
            ['id' => 10, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '24454'],
            ['id' => 11, 'provinsi_id' => 21, 'kabupaten' => 'Aceh Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '24382'],
            ['id' => 12, 'provinsi_id' => 32, 'kabupaten' => 'Agam', 'tipe' => 'Kabupaten', 'kode_pos' => '26411'],
            ['id' => 13, 'provinsi_id' => 23, 'kabupaten' => 'Alor', 'tipe' => 'Kabupaten', 'kode_pos' => '85811'],
            ['id' => 14, 'provinsi_id' => 19, 'kabupaten' => 'Ambon', 'tipe' => 'Kota', 'kode_pos' => '97222'],
            ['id' => 15, 'provinsi_id' => 34, 'kabupaten' => 'Asahan', 'tipe' => 'Kabupaten', 'kode_pos' => '21214'],
            ['id' => 16, 'provinsi_id' => 24, 'kabupaten' => 'Asmat', 'tipe' => 'Kabupaten', 'kode_pos' => '99777'],
            ['id' => 17, 'provinsi_id' => 1, 'kabupaten' => 'Badung', 'tipe' => 'Kabupaten', 'kode_pos' => '80351'],
            ['id' => 18, 'provinsi_id' => 13, 'kabupaten' => 'Balangan', 'tipe' => 'Kabupaten', 'kode_pos' => '71611'],
            ['id' => 19, 'provinsi_id' => 15, 'kabupaten' => 'Balikpapan', 'tipe' => 'Kota', 'kode_pos' => '76111'],
            ['id' => 20, 'provinsi_id' => 21, 'kabupaten' => 'Banda Aceh', 'tipe' => 'Kota', 'kode_pos' => '23238'],
            ['id' => 21, 'provinsi_id' => 18, 'kabupaten' => 'Bandar Lampung', 'tipe' => 'Kota', 'kode_pos' => '35139'],
            ['id' => 22, 'provinsi_id' => 9, 'kabupaten' => 'Bandung', 'tipe' => 'Kabupaten', 'kode_pos' => '40311'],
            ['id' => 23, 'provinsi_id' => 9, 'kabupaten' => 'Bandung', 'tipe' => 'Kota', 'kode_pos' => '40115'],
            ['id' => 24, 'provinsi_id' => 9, 'kabupaten' => 'Bandung Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '40721'],
            ['id' => 25, 'provinsi_id' => 29, 'kabupaten' => 'Banggai', 'tipe' => 'Kabupaten', 'kode_pos' => '94711'],
            ['id' => 26, 'provinsi_id' => 29, 'kabupaten' => 'Banggai Kepulauan', 'tipe' => 'Kabupaten', 'kode_pos' => '94881'],
            ['id' => 27, 'provinsi_id' => 2, 'kabupaten' => 'Bangka', 'tipe' => 'Kabupaten', 'kode_pos' => '33212'],
            ['id' => 28, 'provinsi_id' => 2, 'kabupaten' => 'Bangka Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '33315'],
            ['id' => 29, 'provinsi_id' => 2, 'kabupaten' => 'Bangka Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '33719'],
            ['id' => 30, 'provinsi_id' => 2, 'kabupaten' => 'Bangka Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '33613'],
            ['id' => 31, 'provinsi_id' => 11, 'kabupaten' => 'Bangkalan', 'tipe' => 'Kabupaten', 'kode_pos' => '69118'],
            ['id' => 32, 'provinsi_id' => 1, 'kabupaten' => 'Bangli', 'tipe' => 'Kabupaten', 'kode_pos' => '80619'],
            ['id' => 33, 'provinsi_id' => 13, 'kabupaten' => 'Banjar', 'tipe' => 'Kabupaten', 'kode_pos' => '70619'],
            ['id' => 34, 'provinsi_id' => 9, 'kabupaten' => 'Banjar', 'tipe' => 'Kota', 'kode_pos' => '46311'],
            ['id' => 35, 'provinsi_id' => 13, 'kabupaten' => 'Banjarbaru', 'tipe' => 'Kota', 'kode_pos' => '70712'],
            ['id' => 36, 'provinsi_id' => 13, 'kabupaten' => 'Banjarmasin', 'tipe' => 'Kota', 'kode_pos' => '70117'],
            ['id' => 37, 'provinsi_id' => 10, 'kabupaten' => 'Banjarnegara', 'tipe' => 'Kabupaten', 'kode_pos' => '53419'],
            ['id' => 38, 'provinsi_id' => 28, 'kabupaten' => 'Bantaeng', 'tipe' => 'Kabupaten', 'kode_pos' => '92411'],
            ['id' => 39, 'provinsi_id' => 5, 'kabupaten' => 'Bantul', 'tipe' => 'Kabupaten', 'kode_pos' => '55715'],
            ['id' => 40, 'provinsi_id' => 33, 'kabupaten' => 'Banyuasin', 'tipe' => 'Kabupaten', 'kode_pos' => '30911'],
            ['id' => 41, 'provinsi_id' => 10, 'kabupaten' => 'Banyumas', 'tipe' => 'Kabupaten', 'kode_pos' => '53114'],
            ['id' => 42, 'provinsi_id' => 11, 'kabupaten' => 'Banyuwangi', 'tipe' => 'Kabupaten', 'kode_pos' => '68416'],
            ['id' => 43, 'provinsi_id' => 13, 'kabupaten' => 'Barito Kuala', 'tipe' => 'Kabupaten', 'kode_pos' => '70511'],
            ['id' => 44, 'provinsi_id' => 14, 'kabupaten' => 'Barito Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '73711'],
            ['id' => 45, 'provinsi_id' => 14, 'kabupaten' => 'Barito Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '73671'],
            ['id' => 46, 'provinsi_id' => 14, 'kabupaten' => 'Barito Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '73881'],
            ['id' => 47, 'provinsi_id' => 28, 'kabupaten' => 'Barru', 'tipe' => 'Kabupaten', 'kode_pos' => '90719'],
            ['id' => 48, 'provinsi_id' => 17, 'kabupaten' => 'Batam', 'tipe' => 'Kota', 'kode_pos' => '29413'],
            ['id' => 49, 'provinsi_id' => 10, 'kabupaten' => 'Batang', 'tipe' => 'Kabupaten', 'kode_pos' => '51211'],
            ['id' => 50, 'provinsi_id' => 8, 'kabupaten' => 'Batang Hari', 'tipe' => 'Kabupaten', 'kode_pos' => '36613'],
            ['id' => 51, 'provinsi_id' => 11, 'kabupaten' => 'Batu', 'tipe' => 'Kota', 'kode_pos' => '65311'],
            ['id' => 52, 'provinsi_id' => 34, 'kabupaten' => 'Batu Bara', 'tipe' => 'Kabupaten', 'kode_pos' => '21655'],
            ['id' => 53, 'provinsi_id' => 30, 'kabupaten' => 'Bau-Bau', 'tipe' => 'Kota', 'kode_pos' => '93719'],
            ['id' => 54, 'provinsi_id' => 9, 'kabupaten' => 'Bekasi', 'tipe' => 'Kabupaten', 'kode_pos' => '17837'],
            ['id' => 55, 'provinsi_id' => 9, 'kabupaten' => 'Bekasi', 'tipe' => 'Kota', 'kode_pos' => '17121'],
            ['id' => 56, 'provinsi_id' => 2, 'kabupaten' => 'Belitung', 'tipe' => 'Kabupaten', 'kode_pos' => '33419'],
            ['id' => 57, 'provinsi_id' => 2, 'kabupaten' => 'Belitung Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '33519'],
            ['id' => 58, 'provinsi_id' => 23, 'kabupaten' => 'Belu', 'tipe' => 'Kabupaten', 'kode_pos' => '85711'],
            ['id' => 59, 'provinsi_id' => 21, 'kabupaten' => 'Bener Meriah', 'tipe' => 'Kabupaten', 'kode_pos' => '24581'],
            ['id' => 60, 'provinsi_id' => 26, 'kabupaten' => 'Bengkalis', 'tipe' => 'Kabupaten', 'kode_pos' => '28719'],
            ['id' => 61, 'provinsi_id' => 12, 'kabupaten' => 'Bengkayang', 'tipe' => 'Kabupaten', 'kode_pos' => '79213'],
            ['id' => 62, 'provinsi_id' => 4, 'kabupaten' => 'Bengkulu', 'tipe' => 'Kota', 'kode_pos' => '38229'],
            ['id' => 63, 'provinsi_id' => 4, 'kabupaten' => 'Bengkulu Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '38519'],
            ['id' => 64, 'provinsi_id' => 4, 'kabupaten' => 'Bengkulu Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '38319'],
            ['id' => 65, 'provinsi_id' => 4, 'kabupaten' => 'Bengkulu Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '38619'],
            ['id' => 66, 'provinsi_id' => 15, 'kabupaten' => 'Berau', 'tipe' => 'Kabupaten', 'kode_pos' => '77311'],
            ['id' => 67, 'provinsi_id' => 24, 'kabupaten' => 'Biak Numfor', 'tipe' => 'Kabupaten', 'kode_pos' => '98119'],
            ['id' => 68, 'provinsi_id' => 22, 'kabupaten' => 'Bima', 'tipe' => 'Kabupaten', 'kode_pos' => '84171'],
            ['id' => 69, 'provinsi_id' => 22, 'kabupaten' => 'Bima', 'tipe' => 'Kota', 'kode_pos' => '84139'],
            ['id' => 70, 'provinsi_id' => 34, 'kabupaten' => 'Binjai', 'tipe' => 'Kota', 'kode_pos' => '20712'],
            ['id' => 71, 'provinsi_id' => 17, 'kabupaten' => 'Bintan', 'tipe' => 'Kabupaten', 'kode_pos' => '29135'],
            ['id' => 72, 'provinsi_id' => 21, 'kabupaten' => 'Bireuen', 'tipe' => 'Kabupaten', 'kode_pos' => '24219'],
            ['id' => 73, 'provinsi_id' => 31, 'kabupaten' => 'Bitung', 'tipe' => 'Kota', 'kode_pos' => '95512'],
            ['id' => 74, 'provinsi_id' => 11, 'kabupaten' => 'Blitar', 'tipe' => 'Kabupaten', 'kode_pos' => '66171'],
            ['id' => 75, 'provinsi_id' => 11, 'kabupaten' => 'Blitar', 'tipe' => 'Kota', 'kode_pos' => '66124'],
            ['id' => 76, 'provinsi_id' => 10, 'kabupaten' => 'Blora', 'tipe' => 'Kabupaten', 'kode_pos' => '58219'],
            ['id' => 77, 'provinsi_id' => 7, 'kabupaten' => 'Boalemo', 'tipe' => 'Kabupaten', 'kode_pos' => '96319'],
            ['id' => 78, 'provinsi_id' => 9, 'kabupaten' => 'Bogor', 'tipe' => 'Kabupaten', 'kode_pos' => '16911'],
            ['id' => 79, 'provinsi_id' => 9, 'kabupaten' => 'Bogor', 'tipe' => 'Kota', 'kode_pos' => '16119'],
            ['id' => 80, 'provinsi_id' => 11, 'kabupaten' => 'Bojonegoro', 'tipe' => 'Kabupaten', 'kode_pos' => '62119'],
            ['id' => 81, 'provinsi_id' => 31, 'kabupaten' => 'Bolaang Mongondow (Bolmong)', 'tipe' => 'Kabupaten', 'kode_pos' => '95755'],
            ['id' => 82, 'provinsi_id' => 31, 'kabupaten' => 'Bolaang Mongondow Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '95774'],
            ['id' => 83, 'provinsi_id' => 31, 'kabupaten' => 'Bolaang Mongondow Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '95783'],
            ['id' => 84, 'provinsi_id' => 31, 'kabupaten' => 'Bolaang Mongondow Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '95765'],
            ['id' => 85, 'provinsi_id' => 30, 'kabupaten' => 'Bombana', 'tipe' => 'Kabupaten', 'kode_pos' => '93771'],
            ['id' => 86, 'provinsi_id' => 11, 'kabupaten' => 'Bondowoso', 'tipe' => 'Kabupaten', 'kode_pos' => '68219'],
            ['id' => 87, 'provinsi_id' => 28, 'kabupaten' => 'Bone', 'tipe' => 'Kabupaten', 'kode_pos' => '92713'],
            ['id' => 88, 'provinsi_id' => 7, 'kabupaten' => 'Bone Bolango', 'tipe' => 'Kabupaten', 'kode_pos' => '96511'],
            ['id' => 89, 'provinsi_id' => 15, 'kabupaten' => 'Bontang', 'tipe' => 'Kota', 'kode_pos' => '75313'],
            ['id' => 90, 'provinsi_id' => 24, 'kabupaten' => 'Boven Digoel', 'tipe' => 'Kabupaten', 'kode_pos' => '99662'],
            ['id' => 91, 'provinsi_id' => 10, 'kabupaten' => 'Boyolali', 'tipe' => 'Kabupaten', 'kode_pos' => '57312'],
            ['id' => 92, 'provinsi_id' => 10, 'kabupaten' => 'Brebes', 'tipe' => 'Kabupaten', 'kode_pos' => '52212'],
            ['id' => 93, 'provinsi_id' => 32, 'kabupaten' => 'Bukittinggi', 'tipe' => 'Kota', 'kode_pos' => '26115'],
            ['id' => 94, 'provinsi_id' => 1, 'kabupaten' => 'Buleleng', 'tipe' => 'Kabupaten', 'kode_pos' => '81111'],
            ['id' => 95, 'provinsi_id' => 28, 'kabupaten' => 'Bulukumba', 'tipe' => 'Kabupaten', 'kode_pos' => '92511'],
            ['id' => 96, 'provinsi_id' => 16, 'kabupaten' => 'Bulungan (Bulongan)', 'tipe' => 'Kabupaten', 'kode_pos' => '77211'],
            ['id' => 97, 'provinsi_id' => 8, 'kabupaten' => 'Bungo', 'tipe' => 'Kabupaten', 'kode_pos' => '37216'],
            ['id' => 98, 'provinsi_id' => 29, 'kabupaten' => 'Buol', 'tipe' => 'Kabupaten', 'kode_pos' => '94564'],
            ['id' => 99, 'provinsi_id' => 19, 'kabupaten' => 'Buru', 'tipe' => 'Kabupaten', 'kode_pos' => '97371'],
            ['id' => 100, 'provinsi_id' => 19, 'kabupaten' => 'Buru Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '97351'],
            ['id' => 101, 'provinsi_id' => 30, 'kabupaten' => 'Buton', 'tipe' => 'Kabupaten', 'kode_pos' => '93754'],
            ['id' => 102, 'provinsi_id' => 30, 'kabupaten' => 'Buton Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '93745'],
            ['id' => 103, 'provinsi_id' => 9, 'kabupaten' => 'Ciamis', 'tipe' => 'Kabupaten', 'kode_pos' => '46211'],
            ['id' => 104, 'provinsi_id' => 9, 'kabupaten' => 'Cianjur', 'tipe' => 'Kabupaten', 'kode_pos' => '43217'],
            ['id' => 105, 'provinsi_id' => 10, 'kabupaten' => 'Cilacap', 'tipe' => 'Kabupaten', 'kode_pos' => '53211'],
            ['id' => 106, 'provinsi_id' => 3, 'kabupaten' => 'Cilegon', 'tipe' => 'Kota', 'kode_pos' => '42417'],
            ['id' => 107, 'provinsi_id' => 9, 'kabupaten' => 'Cimahi', 'tipe' => 'Kota', 'kode_pos' => '40512'],
            ['id' => 108, 'provinsi_id' => 9, 'kabupaten' => 'Cirebon', 'tipe' => 'Kabupaten', 'kode_pos' => '45611'],
            ['id' => 109, 'provinsi_id' => 9, 'kabupaten' => 'Cirebon', 'tipe' => 'Kota', 'kode_pos' => '45116'],
            ['id' => 110, 'provinsi_id' => 34, 'kabupaten' => 'Dairi', 'tipe' => 'Kabupaten', 'kode_pos' => '22211'],
            ['id' => 111, 'provinsi_id' => 24, 'kabupaten' => 'Deiyai (Deliyai)', 'tipe' => 'Kabupaten', 'kode_pos' => '98784'],
            ['id' => 112, 'provinsi_id' => 34, 'kabupaten' => 'Deli Serdang', 'tipe' => 'Kabupaten', 'kode_pos' => '20511'],
            ['id' => 113, 'provinsi_id' => 10, 'kabupaten' => 'Demak', 'tipe' => 'Kabupaten', 'kode_pos' => '59519'],
            ['id' => 114, 'provinsi_id' => 1, 'kabupaten' => 'Denpasar', 'tipe' => 'Kota', 'kode_pos' => '80227'],
            ['id' => 115, 'provinsi_id' => 9, 'kabupaten' => 'Depok', 'tipe' => 'Kota', 'kode_pos' => '16416'],
            ['id' => 116, 'provinsi_id' => 32, 'kabupaten' => 'Dharmasraya', 'tipe' => 'Kabupaten', 'kode_pos' => '27612'],
            ['id' => 117, 'provinsi_id' => 24, 'kabupaten' => 'Dogiyai', 'tipe' => 'Kabupaten', 'kode_pos' => '98866'],
            ['id' => 118, 'provinsi_id' => 22, 'kabupaten' => 'Dompu', 'tipe' => 'Kabupaten', 'kode_pos' => '84217'],
            ['id' => 119, 'provinsi_id' => 29, 'kabupaten' => 'Donggala', 'tipe' => 'Kabupaten', 'kode_pos' => '94341'],
            ['id' => 120, 'provinsi_id' => 26, 'kabupaten' => 'Dumai', 'tipe' => 'Kota', 'kode_pos' => '28811'],
            ['id' => 121, 'provinsi_id' => 33, 'kabupaten' => 'Empat Lawang', 'tipe' => 'Kabupaten', 'kode_pos' => '31811'],
            ['id' => 122, 'provinsi_id' => 23, 'kabupaten' => 'Ende', 'tipe' => 'Kabupaten', 'kode_pos' => '86351'],
            ['id' => 123, 'provinsi_id' => 28, 'kabupaten' => 'Enrekang', 'tipe' => 'Kabupaten', 'kode_pos' => '91719'],
            ['id' => 124, 'provinsi_id' => 25, 'kabupaten' => 'Fakfak', 'tipe' => 'Kabupaten', 'kode_pos' => '98651'],
            ['id' => 125, 'provinsi_id' => 23, 'kabupaten' => 'Flores Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '86213'],
            ['id' => 126, 'provinsi_id' => 9, 'kabupaten' => 'Garut', 'tipe' => 'Kabupaten', 'kode_pos' => '44126'],
            ['id' => 127, 'provinsi_id' => 21, 'kabupaten' => 'Gayo Lues', 'tipe' => 'Kabupaten', 'kode_pos' => '24653'],
            ['id' => 128, 'provinsi_id' => 1, 'kabupaten' => 'Gianyar', 'tipe' => 'Kabupaten', 'kode_pos' => '80519'],
            ['id' => 129, 'provinsi_id' => 7, 'kabupaten' => 'Gorontalo', 'tipe' => 'Kabupaten', 'kode_pos' => '96218'],
            ['id' => 130, 'provinsi_id' => 7, 'kabupaten' => 'Gorontalo', 'tipe' => 'Kota', 'kode_pos' => '96115'],
            ['id' => 131, 'provinsi_id' => 7, 'kabupaten' => 'Gorontalo Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '96611'],
            ['id' => 132, 'provinsi_id' => 28, 'kabupaten' => 'Gowa', 'tipe' => 'Kabupaten', 'kode_pos' => '92111'],
            ['id' => 133, 'provinsi_id' => 11, 'kabupaten' => 'Gresik', 'tipe' => 'Kabupaten', 'kode_pos' => '61115'],
            ['id' => 134, 'provinsi_id' => 10, 'kabupaten' => 'Grobogan', 'tipe' => 'Kabupaten', 'kode_pos' => '58111'],
            ['id' => 135, 'provinsi_id' => 5, 'kabupaten' => 'Gunung Kidul', 'tipe' => 'Kabupaten', 'kode_pos' => '55812'],
            ['id' => 136, 'provinsi_id' => 14, 'kabupaten' => 'Gunung Mas', 'tipe' => 'Kabupaten', 'kode_pos' => '74511'],
            ['id' => 137, 'provinsi_id' => 34, 'kabupaten' => 'Gunungsitoli', 'tipe' => 'Kota', 'kode_pos' => '22813'],
            ['id' => 138, 'provinsi_id' => 20, 'kabupaten' => 'Halmahera Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '97757'],
            ['id' => 139, 'provinsi_id' => 20, 'kabupaten' => 'Halmahera Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '97911'],
            ['id' => 140, 'provinsi_id' => 20, 'kabupaten' => 'Halmahera Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '97853'],
            ['id' => 141, 'provinsi_id' => 20, 'kabupaten' => 'Halmahera Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '97862'],
            ['id' => 142, 'provinsi_id' => 20, 'kabupaten' => 'Halmahera Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '97762'],
            ['id' => 143, 'provinsi_id' => 13, 'kabupaten' => 'Hulu Sungai Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '71212'],
            ['id' => 144, 'provinsi_id' => 13, 'kabupaten' => 'Hulu Sungai Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '71313'],
            ['id' => 145, 'provinsi_id' => 13, 'kabupaten' => 'Hulu Sungai Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '71419'],
            ['id' => 146, 'provinsi_id' => 34, 'kabupaten' => 'Humbang Hasundutan', 'tipe' => 'Kabupaten', 'kode_pos' => '22457'],
            ['id' => 147, 'provinsi_id' => 26, 'kabupaten' => 'Indragiri Hilir', 'tipe' => 'Kabupaten', 'kode_pos' => '29212'],
            ['id' => 148, 'provinsi_id' => 26, 'kabupaten' => 'Indragiri Hulu', 'tipe' => 'Kabupaten', 'kode_pos' => '29319'],
            ['id' => 149, 'provinsi_id' => 9, 'kabupaten' => 'Indramayu', 'tipe' => 'Kabupaten', 'kode_pos' => '45214'],
            ['id' => 150, 'provinsi_id' => 24, 'kabupaten' => 'Intan Jaya', 'tipe' => 'Kabupaten', 'kode_pos' => '98771'],
            ['id' => 151, 'provinsi_id' => 6, 'kabupaten' => 'Jakarta Barat', 'tipe' => 'Kota', 'kode_pos' => '11220'],
            ['id' => 152, 'provinsi_id' => 6, 'kabupaten' => 'Jakarta Pusat', 'tipe' => 'Kota', 'kode_pos' => '10540'],
            ['id' => 153, 'provinsi_id' => 6, 'kabupaten' => 'Jakarta Selatan', 'tipe' => 'Kota', 'kode_pos' => '12230'],
            ['id' => 154, 'provinsi_id' => 6, 'kabupaten' => 'Jakarta Timur', 'tipe' => 'Kota', 'kode_pos' => '13330'],
            ['id' => 155, 'provinsi_id' => 6, 'kabupaten' => 'Jakarta Utara', 'tipe' => 'Kota', 'kode_pos' => '14140'],
            ['id' => 156, 'provinsi_id' => 8, 'kabupaten' => 'Jambi', 'tipe' => 'Kota', 'kode_pos' => '36111'],
            ['id' => 157, 'provinsi_id' => 24, 'kabupaten' => 'Jayapura', 'tipe' => 'Kabupaten', 'kode_pos' => '99352'],
            ['id' => 158, 'provinsi_id' => 24, 'kabupaten' => 'Jayapura', 'tipe' => 'Kota', 'kode_pos' => '99114'],
            ['id' => 159, 'provinsi_id' => 24, 'kabupaten' => 'Jayawijaya', 'tipe' => 'Kabupaten', 'kode_pos' => '99511'],
            ['id' => 160, 'provinsi_id' => 11, 'kabupaten' => 'Jember', 'tipe' => 'Kabupaten', 'kode_pos' => '68113'],
            ['id' => 161, 'provinsi_id' => 1, 'kabupaten' => 'Jembrana', 'tipe' => 'Kabupaten', 'kode_pos' => '82251'],
            ['id' => 162, 'provinsi_id' => 28, 'kabupaten' => 'Jeneponto', 'tipe' => 'Kabupaten', 'kode_pos' => '92319'],
            ['id' => 163, 'provinsi_id' => 10, 'kabupaten' => 'Jepara', 'tipe' => 'Kabupaten', 'kode_pos' => '59419'],
            ['id' => 164, 'provinsi_id' => 11, 'kabupaten' => 'Jombang', 'tipe' => 'Kabupaten', 'kode_pos' => '61415'],
            ['id' => 165, 'provinsi_id' => 25, 'kabupaten' => 'Kaimana', 'tipe' => 'Kabupaten', 'kode_pos' => '98671'],
            ['id' => 166, 'provinsi_id' => 26, 'kabupaten' => 'Kampar', 'tipe' => 'Kabupaten', 'kode_pos' => '28411'],
            ['id' => 167, 'provinsi_id' => 14, 'kabupaten' => 'Kapuas', 'tipe' => 'Kabupaten', 'kode_pos' => '73583'],
            ['id' => 168, 'provinsi_id' => 12, 'kabupaten' => 'Kapuas Hulu', 'tipe' => 'Kabupaten', 'kode_pos' => '78719'],
            ['id' => 169, 'provinsi_id' => 10, 'kabupaten' => 'Karanganyar', 'tipe' => 'Kabupaten', 'kode_pos' => '57718'],
            ['id' => 170, 'provinsi_id' => 1, 'kabupaten' => 'Karangasem', 'tipe' => 'Kabupaten', 'kode_pos' => '80819'],
            ['id' => 171, 'provinsi_id' => 9, 'kabupaten' => 'Karawang', 'tipe' => 'Kabupaten', 'kode_pos' => '41311'],
            ['id' => 172, 'provinsi_id' => 17, 'kabupaten' => 'Karimun', 'tipe' => 'Kabupaten', 'kode_pos' => '29611'],
            ['id' => 173, 'provinsi_id' => 34, 'kabupaten' => 'Karo', 'tipe' => 'Kabupaten', 'kode_pos' => '22119'],
            ['id' => 174, 'provinsi_id' => 14, 'kabupaten' => 'Katingan', 'tipe' => 'Kabupaten', 'kode_pos' => '74411'],
            ['id' => 175, 'provinsi_id' => 4, 'kabupaten' => 'Kaur', 'tipe' => 'Kabupaten', 'kode_pos' => '38911'],
            ['id' => 176, 'provinsi_id' => 12, 'kabupaten' => 'Kayong Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '78852'],
            ['id' => 177, 'provinsi_id' => 10, 'kabupaten' => 'Kebumen', 'tipe' => 'Kabupaten', 'kode_pos' => '54319'],
            ['id' => 178, 'provinsi_id' => 11, 'kabupaten' => 'Kediri', 'tipe' => 'Kabupaten', 'kode_pos' => '64184'],
            ['id' => 179, 'provinsi_id' => 11, 'kabupaten' => 'Kediri', 'tipe' => 'Kota', 'kode_pos' => '64125'],
            ['id' => 180, 'provinsi_id' => 24, 'kabupaten' => 'Keerom', 'tipe' => 'Kabupaten', 'kode_pos' => '99461'],
            ['id' => 181, 'provinsi_id' => 10, 'kabupaten' => 'Kendal', 'tipe' => 'Kabupaten', 'kode_pos' => '51314'],
            ['id' => 182, 'provinsi_id' => 30, 'kabupaten' => 'Kendari', 'tipe' => 'Kota', 'kode_pos' => '93126'],
            ['id' => 183, 'provinsi_id' => 4, 'kabupaten' => 'Kepahiang', 'tipe' => 'Kabupaten', 'kode_pos' => '39319'],
            ['id' => 184, 'provinsi_id' => 17, 'kabupaten' => 'Kepulauan Anambas', 'tipe' => 'Kabupaten', 'kode_pos' => '29991'],
            ['id' => 185, 'provinsi_id' => 19, 'kabupaten' => 'Kepulauan Aru', 'tipe' => 'Kabupaten', 'kode_pos' => '97681'],
            ['id' => 186, 'provinsi_id' => 32, 'kabupaten' => 'Kepulauan Mentawai', 'tipe' => 'Kabupaten', 'kode_pos' => '25771'],
            ['id' => 187, 'provinsi_id' => 26, 'kabupaten' => 'Kepulauan Meranti', 'tipe' => 'Kabupaten', 'kode_pos' => '28791'],
            ['id' => 188, 'provinsi_id' => 31, 'kabupaten' => 'Kepulauan Sangihe', 'tipe' => 'Kabupaten', 'kode_pos' => '95819'],
            ['id' => 189, 'provinsi_id' => 6, 'kabupaten' => 'Kepulauan Seribu', 'tipe' => 'Kabupaten', 'kode_pos' => '14550'],
            ['id' => 190, 'provinsi_id' => 31, 'kabupaten' => 'Kepulauan Siau Tagulandang Biaro (Sitaro)', 'tipe' => 'Kabupaten', 'kode_pos' => '95862'],
            ['id' => 191, 'provinsi_id' => 20, 'kabupaten' => 'Kepulauan Sula', 'tipe' => 'Kabupaten', 'kode_pos' => '97995'],
            ['id' => 192, 'provinsi_id' => 31, 'kabupaten' => 'Kepulauan Talaud', 'tipe' => 'Kabupaten', 'kode_pos' => '95885'],
            ['id' => 193, 'provinsi_id' => 24, 'kabupaten' => 'Kepulauan Yapen (Yapen Waropen)', 'tipe' => 'Kabupaten', 'kode_pos' => '98211'],
            ['id' => 194, 'provinsi_id' => 8, 'kabupaten' => 'Kerinci', 'tipe' => 'Kabupaten', 'kode_pos' => '37167'],
            ['id' => 195, 'provinsi_id' => 12, 'kabupaten' => 'Ketapang', 'tipe' => 'Kabupaten', 'kode_pos' => '78874'],
            ['id' => 196, 'provinsi_id' => 10, 'kabupaten' => 'Klaten', 'tipe' => 'Kabupaten', 'kode_pos' => '57411'],
            ['id' => 197, 'provinsi_id' => 1, 'kabupaten' => 'Klungkung', 'tipe' => 'Kabupaten', 'kode_pos' => '80719'],
            ['id' => 198, 'provinsi_id' => 30, 'kabupaten' => 'Kolaka', 'tipe' => 'Kabupaten', 'kode_pos' => '93511'],
            ['id' => 199, 'provinsi_id' => 30, 'kabupaten' => 'Kolaka Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '93911'],
            ['id' => 200, 'provinsi_id' => 30, 'kabupaten' => 'Konawe', 'tipe' => 'Kabupaten', 'kode_pos' => '93411'],
            ['id' => 201, 'provinsi_id' => 30, 'kabupaten' => 'Konawe Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '93811'],
            ['id' => 202, 'provinsi_id' => 30, 'kabupaten' => 'Konawe Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '93311'],
            ['id' => 203, 'provinsi_id' => 13, 'kabupaten' => 'Kotabaru', 'tipe' => 'Kabupaten', 'kode_pos' => '72119'],
            ['id' => 204, 'provinsi_id' => 31, 'kabupaten' => 'Kotamobagu', 'tipe' => 'Kota', 'kode_pos' => '95711'],
            ['id' => 205, 'provinsi_id' => 14, 'kabupaten' => 'Kotawaringin Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '74119'],
            ['id' => 206, 'provinsi_id' => 14, 'kabupaten' => 'Kotawaringin Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '74364'],
            ['id' => 207, 'provinsi_id' => 26, 'kabupaten' => 'Kuantan Singingi', 'tipe' => 'Kabupaten', 'kode_pos' => '29519'],
            ['id' => 208, 'provinsi_id' => 12, 'kabupaten' => 'Kubu Raya', 'tipe' => 'Kabupaten', 'kode_pos' => '78311'],
            ['id' => 209, 'provinsi_id' => 10, 'kabupaten' => 'Kudus', 'tipe' => 'Kabupaten', 'kode_pos' => '59311'],
            ['id' => 210, 'provinsi_id' => 5, 'kabupaten' => 'Kulon Progo', 'tipe' => 'Kabupaten', 'kode_pos' => '55611'],
            ['id' => 211, 'provinsi_id' => 9, 'kabupaten' => 'Kuningan', 'tipe' => 'Kabupaten', 'kode_pos' => '45511'],
            ['id' => 212, 'provinsi_id' => 23, 'kabupaten' => 'Kupang', 'tipe' => 'Kabupaten', 'kode_pos' => '85362'],
            ['id' => 213, 'provinsi_id' => 23, 'kabupaten' => 'Kupang', 'tipe' => 'Kota', 'kode_pos' => '85119'],
            ['id' => 214, 'provinsi_id' => 15, 'kabupaten' => 'Kutai Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '75711'],
            ['id' => 215, 'provinsi_id' => 15, 'kabupaten' => 'Kutai Kartanegara', 'tipe' => 'Kabupaten', 'kode_pos' => '75511'],
            ['id' => 216, 'provinsi_id' => 15, 'kabupaten' => 'Kutai Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '75611'],
            ['id' => 217, 'provinsi_id' => 34, 'kabupaten' => 'Labuhan Batu', 'tipe' => 'Kabupaten', 'kode_pos' => '21412'],
            ['id' => 218, 'provinsi_id' => 34, 'kabupaten' => 'Labuhan Batu Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '21511'],
            ['id' => 219, 'provinsi_id' => 34, 'kabupaten' => 'Labuhan Batu Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '21711'],
            ['id' => 220, 'provinsi_id' => 33, 'kabupaten' => 'Lahat', 'tipe' => 'Kabupaten', 'kode_pos' => '31419'],
            ['id' => 221, 'provinsi_id' => 14, 'kabupaten' => 'Lamandau', 'tipe' => 'Kabupaten', 'kode_pos' => '74611'],
            ['id' => 222, 'provinsi_id' => 11, 'kabupaten' => 'Lamongan', 'tipe' => 'Kabupaten', 'kode_pos' => '64125'],
            ['id' => 223, 'provinsi_id' => 18, 'kabupaten' => 'Lampung Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '34814'],
            ['id' => 224, 'provinsi_id' => 18, 'kabupaten' => 'Lampung Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '35511'],
            ['id' => 225, 'provinsi_id' => 18, 'kabupaten' => 'Lampung Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '34212'],
            ['id' => 226, 'provinsi_id' => 18, 'kabupaten' => 'Lampung Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '34319'],
            ['id' => 227, 'provinsi_id' => 18, 'kabupaten' => 'Lampung Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '34516'],
            ['id' => 228, 'provinsi_id' => 12, 'kabupaten' => 'Landak', 'tipe' => 'Kabupaten', 'kode_pos' => '78319'],
            ['id' => 229, 'provinsi_id' => 34, 'kabupaten' => 'Langkat', 'tipe' => 'Kabupaten', 'kode_pos' => '20811'],
            ['id' => 230, 'provinsi_id' => 21, 'kabupaten' => 'Langsa', 'tipe' => 'Kota', 'kode_pos' => '24412'],
            ['id' => 231, 'provinsi_id' => 24, 'kabupaten' => 'Lanny Jaya', 'tipe' => 'Kabupaten', 'kode_pos' => '99531'],
            ['id' => 232, 'provinsi_id' => 3, 'kabupaten' => 'Lebak', 'tipe' => 'Kabupaten', 'kode_pos' => '42319'],
            ['id' => 233, 'provinsi_id' => 4, 'kabupaten' => 'Lebong', 'tipe' => 'Kabupaten', 'kode_pos' => '39264'],
            ['id' => 234, 'provinsi_id' => 23, 'kabupaten' => 'Lembata', 'tipe' => 'Kabupaten', 'kode_pos' => '86611'],
            ['id' => 235, 'provinsi_id' => 21, 'kabupaten' => 'Lhokseumawe', 'tipe' => 'Kota', 'kode_pos' => '24352'],
            ['id' => 236, 'provinsi_id' => 32, 'kabupaten' => 'Lima Puluh Koto/Kota', 'tipe' => 'Kabupaten', 'kode_pos' => '26671'],
            ['id' => 237, 'provinsi_id' => 17, 'kabupaten' => 'Lingga', 'tipe' => 'Kabupaten', 'kode_pos' => '29811'],
            ['id' => 238, 'provinsi_id' => 22, 'kabupaten' => 'Lombok Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '83311'],
            ['id' => 239, 'provinsi_id' => 22, 'kabupaten' => 'Lombok Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '83511'],
            ['id' => 240, 'provinsi_id' => 22, 'kabupaten' => 'Lombok Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '83612'],
            ['id' => 241, 'provinsi_id' => 22, 'kabupaten' => 'Lombok Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '83711'],
            ['id' => 242, 'provinsi_id' => 33, 'kabupaten' => 'Lubuk Linggau', 'tipe' => 'Kota', 'kode_pos' => '31614'],
            ['id' => 243, 'provinsi_id' => 11, 'kabupaten' => 'Lumajang', 'tipe' => 'Kabupaten', 'kode_pos' => '67319'],
            ['id' => 244, 'provinsi_id' => 28, 'kabupaten' => 'Luwu', 'tipe' => 'Kabupaten', 'kode_pos' => '91994'],
            ['id' => 245, 'provinsi_id' => 28, 'kabupaten' => 'Luwu Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '92981'],
            ['id' => 246, 'provinsi_id' => 28, 'kabupaten' => 'Luwu Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '92911'],
            ['id' => 247, 'provinsi_id' => 11, 'kabupaten' => 'Madiun', 'tipe' => 'Kabupaten', 'kode_pos' => '63153'],
            ['id' => 248, 'provinsi_id' => 11, 'kabupaten' => 'Madiun', 'tipe' => 'Kota', 'kode_pos' => '63122'],
            ['id' => 249, 'provinsi_id' => 10, 'kabupaten' => 'Magelang', 'tipe' => 'Kabupaten', 'kode_pos' => '56519'],
            ['id' => 250, 'provinsi_id' => 10, 'kabupaten' => 'Magelang', 'tipe' => 'Kota', 'kode_pos' => '56133'],
            ['id' => 251, 'provinsi_id' => 11, 'kabupaten' => 'Magetan', 'tipe' => 'Kabupaten', 'kode_pos' => '63314'],
            ['id' => 252, 'provinsi_id' => 9, 'kabupaten' => 'Majalengka', 'tipe' => 'Kabupaten', 'kode_pos' => '45412'],
            ['id' => 253, 'provinsi_id' => 27, 'kabupaten' => 'Majene', 'tipe' => 'Kabupaten', 'kode_pos' => '91411'],
            ['id' => 254, 'provinsi_id' => 28, 'kabupaten' => 'Makassar', 'tipe' => 'Kota', 'kode_pos' => '90111'],
            ['id' => 255, 'provinsi_id' => 11, 'kabupaten' => 'Malang', 'tipe' => 'Kabupaten', 'kode_pos' => '65163'],
            ['id' => 256, 'provinsi_id' => 11, 'kabupaten' => 'Malang', 'tipe' => 'Kota', 'kode_pos' => '65112'],
            ['id' => 257, 'provinsi_id' => 16, 'kabupaten' => 'Malinau', 'tipe' => 'Kabupaten', 'kode_pos' => '77511'],
            ['id' => 258, 'provinsi_id' => 19, 'kabupaten' => 'Maluku Barat Daya', 'tipe' => 'Kabupaten', 'kode_pos' => '97451'],
            ['id' => 259, 'provinsi_id' => 19, 'kabupaten' => 'Maluku Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '97513'],
            ['id' => 260, 'provinsi_id' => 19, 'kabupaten' => 'Maluku Tenggara', 'tipe' => 'Kabupaten', 'kode_pos' => '97651'],
            ['id' => 261, 'provinsi_id' => 19, 'kabupaten' => 'Maluku Tenggara Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '97465'],
            ['id' => 262, 'provinsi_id' => 27, 'kabupaten' => 'Mamasa', 'tipe' => 'Kabupaten', 'kode_pos' => '91362'],
            ['id' => 263, 'provinsi_id' => 24, 'kabupaten' => 'Mamberamo Raya', 'tipe' => 'Kabupaten', 'kode_pos' => '99381'],
            ['id' => 264, 'provinsi_id' => 24, 'kabupaten' => 'Mamberamo Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '99553'],
            ['id' => 265, 'provinsi_id' => 27, 'kabupaten' => 'Mamuju', 'tipe' => 'Kabupaten', 'kode_pos' => '91519'],
            ['id' => 266, 'provinsi_id' => 27, 'kabupaten' => 'Mamuju Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '91571'],
            ['id' => 267, 'provinsi_id' => 31, 'kabupaten' => 'Manado', 'tipe' => 'Kota', 'kode_pos' => '95247'],
            ['id' => 268, 'provinsi_id' => 34, 'kabupaten' => 'Mandailing Natal', 'tipe' => 'Kabupaten', 'kode_pos' => '22916'],
            ['id' => 269, 'provinsi_id' => 23, 'kabupaten' => 'Manggarai', 'tipe' => 'Kabupaten', 'kode_pos' => '86551'],
            ['id' => 270, 'provinsi_id' => 23, 'kabupaten' => 'Manggarai Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '86711'],
            ['id' => 271, 'provinsi_id' => 23, 'kabupaten' => 'Manggarai Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '86811'],
            ['id' => 272, 'provinsi_id' => 25, 'kabupaten' => 'Manokwari', 'tipe' => 'Kabupaten', 'kode_pos' => '98311'],
            ['id' => 273, 'provinsi_id' => 25, 'kabupaten' => 'Manokwari Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '98355'],
            ['id' => 274, 'provinsi_id' => 24, 'kabupaten' => 'Mappi', 'tipe' => 'Kabupaten', 'kode_pos' => '99853'],
            ['id' => 275, 'provinsi_id' => 28, 'kabupaten' => 'Maros', 'tipe' => 'Kabupaten', 'kode_pos' => '90511'],
            ['id' => 276, 'provinsi_id' => 22, 'kabupaten' => 'Mataram', 'tipe' => 'Kota', 'kode_pos' => '83131'],
            ['id' => 277, 'provinsi_id' => 25, 'kabupaten' => 'Maybrat', 'tipe' => 'Kabupaten', 'kode_pos' => '98051'],
            ['id' => 278, 'provinsi_id' => 34, 'kabupaten' => 'Medan', 'tipe' => 'Kota', 'kode_pos' => '20228'],
            ['id' => 279, 'provinsi_id' => 12, 'kabupaten' => 'Melawi', 'tipe' => 'Kabupaten', 'kode_pos' => '78619'],
            ['id' => 280, 'provinsi_id' => 8, 'kabupaten' => 'Merangin', 'tipe' => 'Kabupaten', 'kode_pos' => '37319'],
            ['id' => 281, 'provinsi_id' => 24, 'kabupaten' => 'Merauke', 'tipe' => 'Kabupaten', 'kode_pos' => '99613'],
            ['id' => 282, 'provinsi_id' => 18, 'kabupaten' => 'Mesuji', 'tipe' => 'Kabupaten', 'kode_pos' => '34911'],
            ['id' => 283, 'provinsi_id' => 18, 'kabupaten' => 'Metro', 'tipe' => 'Kota', 'kode_pos' => '34111'],
            ['id' => 284, 'provinsi_id' => 24, 'kabupaten' => 'Mimika', 'tipe' => 'Kabupaten', 'kode_pos' => '99962'],
            ['id' => 285, 'provinsi_id' => 31, 'kabupaten' => 'Minahasa', 'tipe' => 'Kabupaten', 'kode_pos' => '95614'],
            ['id' => 286, 'provinsi_id' => 31, 'kabupaten' => 'Minahasa Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '95914'],
            ['id' => 287, 'provinsi_id' => 31, 'kabupaten' => 'Minahasa Tenggara', 'tipe' => 'Kabupaten', 'kode_pos' => '95995'],
            ['id' => 288, 'provinsi_id' => 31, 'kabupaten' => 'Minahasa Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '95316'],
            ['id' => 289, 'provinsi_id' => 11, 'kabupaten' => 'Mojokerto', 'tipe' => 'Kabupaten', 'kode_pos' => '61382'],
            ['id' => 290, 'provinsi_id' => 11, 'kabupaten' => 'Mojokerto', 'tipe' => 'Kota', 'kode_pos' => '61316'],
            ['id' => 291, 'provinsi_id' => 29, 'kabupaten' => 'Morowali', 'tipe' => 'Kabupaten', 'kode_pos' => '94911'],
            ['id' => 292, 'provinsi_id' => 33, 'kabupaten' => 'Muara Enim', 'tipe' => 'Kabupaten', 'kode_pos' => '31315'],
            ['id' => 293, 'provinsi_id' => 8, 'kabupaten' => 'Muaro Jambi', 'tipe' => 'Kabupaten', 'kode_pos' => '36311'],
            ['id' => 294, 'provinsi_id' => 4, 'kabupaten' => 'Muko Muko', 'tipe' => 'Kabupaten', 'kode_pos' => '38715'],
            ['id' => 295, 'provinsi_id' => 30, 'kabupaten' => 'Muna', 'tipe' => 'Kabupaten', 'kode_pos' => '93611'],
            ['id' => 296, 'provinsi_id' => 14, 'kabupaten' => 'Murung Raya', 'tipe' => 'Kabupaten', 'kode_pos' => '73911'],
            ['id' => 297, 'provinsi_id' => 33, 'kabupaten' => 'Musi Banyuasin', 'tipe' => 'Kabupaten', 'kode_pos' => '30719'],
            ['id' => 298, 'provinsi_id' => 33, 'kabupaten' => 'Musi Rawas', 'tipe' => 'Kabupaten', 'kode_pos' => '31661'],
            ['id' => 299, 'provinsi_id' => 24, 'kabupaten' => 'Nabire', 'tipe' => 'Kabupaten', 'kode_pos' => '98816'],
            ['id' => 300, 'provinsi_id' => 21, 'kabupaten' => 'Nagan Raya', 'tipe' => 'Kabupaten', 'kode_pos' => '23674'],
            ['id' => 301, 'provinsi_id' => 23, 'kabupaten' => 'Nagekeo', 'tipe' => 'Kabupaten', 'kode_pos' => '86911'],
            ['id' => 302, 'provinsi_id' => 17, 'kabupaten' => 'Natuna', 'tipe' => 'Kabupaten', 'kode_pos' => '29711'],
            ['id' => 303, 'provinsi_id' => 24, 'kabupaten' => 'Nduga', 'tipe' => 'Kabupaten', 'kode_pos' => '99541'],
            ['id' => 304, 'provinsi_id' => 23, 'kabupaten' => 'Ngada', 'tipe' => 'Kabupaten', 'kode_pos' => '86413'],
            ['id' => 305, 'provinsi_id' => 11, 'kabupaten' => 'Nganjuk', 'tipe' => 'Kabupaten', 'kode_pos' => '64414'],
            ['id' => 306, 'provinsi_id' => 11, 'kabupaten' => 'Ngawi', 'tipe' => 'Kabupaten', 'kode_pos' => '63219'],
            ['id' => 307, 'provinsi_id' => 34, 'kabupaten' => 'Nias', 'tipe' => 'Kabupaten', 'kode_pos' => '22876'],
            ['id' => 308, 'provinsi_id' => 34, 'kabupaten' => 'Nias Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '22895'],
            ['id' => 309, 'provinsi_id' => 34, 'kabupaten' => 'Nias Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '22865'],
            ['id' => 310, 'provinsi_id' => 34, 'kabupaten' => 'Nias Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '22856'],
            ['id' => 311, 'provinsi_id' => 16, 'kabupaten' => 'Nunukan', 'tipe' => 'Kabupaten', 'kode_pos' => '77421'],
            ['id' => 312, 'provinsi_id' => 33, 'kabupaten' => 'Ogan Ilir', 'tipe' => 'Kabupaten', 'kode_pos' => '30811'],
            ['id' => 313, 'provinsi_id' => 33, 'kabupaten' => 'Ogan Komering Ilir', 'tipe' => 'Kabupaten', 'kode_pos' => '30618'],
            ['id' => 314, 'provinsi_id' => 33, 'kabupaten' => 'Ogan Komering Ulu', 'tipe' => 'Kabupaten', 'kode_pos' => '32112'],
            ['id' => 315, 'provinsi_id' => 33, 'kabupaten' => 'Ogan Komering Ulu Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '32211'],
            ['id' => 316, 'provinsi_id' => 33, 'kabupaten' => 'Ogan Komering Ulu Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '32312'],
            ['id' => 317, 'provinsi_id' => 11, 'kabupaten' => 'Pacitan', 'tipe' => 'Kabupaten', 'kode_pos' => '63512'],
            ['id' => 318, 'provinsi_id' => 32, 'kabupaten' => 'Padang', 'tipe' => 'Kota', 'kode_pos' => '25112'],
            ['id' => 319, 'provinsi_id' => 34, 'kabupaten' => 'Padang Lawas', 'tipe' => 'Kabupaten', 'kode_pos' => '22763'],
            ['id' => 320, 'provinsi_id' => 34, 'kabupaten' => 'Padang Lawas Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '22753'],
            ['id' => 321, 'provinsi_id' => 32, 'kabupaten' => 'Padang Panjang', 'tipe' => 'Kota', 'kode_pos' => '27122'],
            ['id' => 322, 'provinsi_id' => 32, 'kabupaten' => 'Padang Pariaman', 'tipe' => 'Kabupaten', 'kode_pos' => '25583'],
            ['id' => 323, 'provinsi_id' => 34, 'kabupaten' => 'Padang Sidempuan', 'tipe' => 'Kota', 'kode_pos' => '22727'],
            ['id' => 324, 'provinsi_id' => 33, 'kabupaten' => 'Pagar Alam', 'tipe' => 'Kota', 'kode_pos' => '31512'],
            ['id' => 325, 'provinsi_id' => 34, 'kabupaten' => 'Pakpak Bharat', 'tipe' => 'Kabupaten', 'kode_pos' => '22272'],
            ['id' => 326, 'provinsi_id' => 14, 'kabupaten' => 'Palangka Raya', 'tipe' => 'Kota', 'kode_pos' => '73112'],
            ['id' => 327, 'provinsi_id' => 33, 'kabupaten' => 'Palembang', 'tipe' => 'Kota', 'kode_pos' => '31512'],
            ['id' => 328, 'provinsi_id' => 28, 'kabupaten' => 'Palopo', 'tipe' => 'Kota', 'kode_pos' => '91911'],
            ['id' => 329, 'provinsi_id' => 29, 'kabupaten' => 'Palu', 'tipe' => 'Kota', 'kode_pos' => '94111'],
            ['id' => 330, 'provinsi_id' => 11, 'kabupaten' => 'Pamekasan', 'tipe' => 'Kabupaten', 'kode_pos' => '69319'],
            ['id' => 331, 'provinsi_id' => 3, 'kabupaten' => 'Pandeglang', 'tipe' => 'Kabupaten', 'kode_pos' => '42212'],
            ['id' => 332, 'provinsi_id' => 9, 'kabupaten' => 'Pangandaran', 'tipe' => 'Kabupaten', 'kode_pos' => '46511'],
            ['id' => 333, 'provinsi_id' => 28, 'kabupaten' => 'Pangkajene Kepulauan', 'tipe' => 'Kabupaten', 'kode_pos' => '90611'],
            ['id' => 334, 'provinsi_id' => 2, 'kabupaten' => 'Pangkal Pinang', 'tipe' => 'Kota', 'kode_pos' => '33115'],
            ['id' => 335, 'provinsi_id' => 24, 'kabupaten' => 'Paniai', 'tipe' => 'Kabupaten', 'kode_pos' => '98765'],
            ['id' => 336, 'provinsi_id' => 28, 'kabupaten' => 'Parepare', 'tipe' => 'Kota', 'kode_pos' => '91123'],
            ['id' => 337, 'provinsi_id' => 32, 'kabupaten' => 'Pariaman', 'tipe' => 'Kota', 'kode_pos' => '25511'],
            ['id' => 338, 'provinsi_id' => 29, 'kabupaten' => 'Parigi Moutong', 'tipe' => 'Kabupaten', 'kode_pos' => '94411'],
            ['id' => 339, 'provinsi_id' => 32, 'kabupaten' => 'Pasaman', 'tipe' => 'Kabupaten', 'kode_pos' => '26318'],
            ['id' => 340, 'provinsi_id' => 32, 'kabupaten' => 'Pasaman Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '26511'],
            ['id' => 341, 'provinsi_id' => 15, 'kabupaten' => 'Paser', 'tipe' => 'Kabupaten', 'kode_pos' => '76211'],
            ['id' => 342, 'provinsi_id' => 11, 'kabupaten' => 'Pasuruan', 'tipe' => 'Kabupaten', 'kode_pos' => '67153'],
            ['id' => 343, 'provinsi_id' => 11, 'kabupaten' => 'Pasuruan', 'tipe' => 'Kota', 'kode_pos' => '67118'],
            ['id' => 344, 'provinsi_id' => 10, 'kabupaten' => 'Pati', 'tipe' => 'Kabupaten', 'kode_pos' => '59114'],
            ['id' => 345, 'provinsi_id' => 32, 'kabupaten' => 'Payakumbuh', 'tipe' => 'Kota', 'kode_pos' => '26213'],
            ['id' => 346, 'provinsi_id' => 25, 'kabupaten' => 'Pegunungan Arfak', 'tipe' => 'Kabupaten', 'kode_pos' => '98354'],
            ['id' => 347, 'provinsi_id' => 24, 'kabupaten' => 'Pegunungan Bintang', 'tipe' => 'Kabupaten', 'kode_pos' => '99573'],
            ['id' => 348, 'provinsi_id' => 10, 'kabupaten' => 'Pekalongan', 'tipe' => 'Kabupaten', 'kode_pos' => '51161'],
            ['id' => 349, 'provinsi_id' => 10, 'kabupaten' => 'Pekalongan', 'tipe' => 'Kota', 'kode_pos' => '51122'],
            ['id' => 350, 'provinsi_id' => 26, 'kabupaten' => 'Pekanbaru', 'tipe' => 'Kota', 'kode_pos' => '28112'],
            ['id' => 351, 'provinsi_id' => 26, 'kabupaten' => 'Pelalawan', 'tipe' => 'Kabupaten', 'kode_pos' => '28311'],
            ['id' => 352, 'provinsi_id' => 10, 'kabupaten' => 'Pemalang', 'tipe' => 'Kabupaten', 'kode_pos' => '52319'],
            ['id' => 353, 'provinsi_id' => 34, 'kabupaten' => 'Pematang Siantar', 'tipe' => 'Kota', 'kode_pos' => '21126'],
            ['id' => 354, 'provinsi_id' => 15, 'kabupaten' => 'Penajam Paser Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '76311'],
            ['id' => 355, 'provinsi_id' => 18, 'kabupaten' => 'Pesawaran', 'tipe' => 'Kabupaten', 'kode_pos' => '35312'],
            ['id' => 356, 'provinsi_id' => 18, 'kabupaten' => 'Pesisir Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '35974'],
            ['id' => 357, 'provinsi_id' => 32, 'kabupaten' => 'Pesisir Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '25611'],
            ['id' => 358, 'provinsi_id' => 21, 'kabupaten' => 'Pidie', 'tipe' => 'Kabupaten', 'kode_pos' => '24116'],
            ['id' => 359, 'provinsi_id' => 21, 'kabupaten' => 'Pidie Jaya', 'tipe' => 'Kabupaten', 'kode_pos' => '24186'],
            ['id' => 360, 'provinsi_id' => 28, 'kabupaten' => 'Pinrang', 'tipe' => 'Kabupaten', 'kode_pos' => '91251'],
            ['id' => 361, 'provinsi_id' => 7, 'kabupaten' => 'Pohuwato', 'tipe' => 'Kabupaten', 'kode_pos' => '96419'],
            ['id' => 362, 'provinsi_id' => 27, 'kabupaten' => 'Polewali Mandar', 'tipe' => 'Kabupaten', 'kode_pos' => '91311'],
            ['id' => 363, 'provinsi_id' => 11, 'kabupaten' => 'Ponorogo', 'tipe' => 'Kabupaten', 'kode_pos' => '63411'],
            ['id' => 364, 'provinsi_id' => 12, 'kabupaten' => 'Pontianak', 'tipe' => 'Kabupaten', 'kode_pos' => '78971'],
            ['id' => 365, 'provinsi_id' => 12, 'kabupaten' => 'Pontianak', 'tipe' => 'Kota', 'kode_pos' => '78112'],
            ['id' => 366, 'provinsi_id' => 29, 'kabupaten' => 'Poso', 'tipe' => 'Kabupaten', 'kode_pos' => '94615'],
            ['id' => 367, 'provinsi_id' => 33, 'kabupaten' => 'Prabumulih', 'tipe' => 'Kota', 'kode_pos' => '31121'],
            ['id' => 368, 'provinsi_id' => 18, 'kabupaten' => 'Pringsewu', 'tipe' => 'Kabupaten', 'kode_pos' => '35719'],
            ['id' => 369, 'provinsi_id' => 11, 'kabupaten' => 'Probolinggo', 'tipe' => 'Kabupaten', 'kode_pos' => '67282'],
            ['id' => 370, 'provinsi_id' => 11, 'kabupaten' => 'Probolinggo', 'tipe' => 'Kota', 'kode_pos' => '67215'],
            ['id' => 371, 'provinsi_id' => 14, 'kabupaten' => 'Pulang Pisau', 'tipe' => 'Kabupaten', 'kode_pos' => '74811'],
            ['id' => 372, 'provinsi_id' => 20, 'kabupaten' => 'Pulau Morotai', 'tipe' => 'Kabupaten', 'kode_pos' => '97771'],
            ['id' => 373, 'provinsi_id' => 24, 'kabupaten' => 'Puncak', 'tipe' => 'Kabupaten', 'kode_pos' => '98981'],
            ['id' => 374, 'provinsi_id' => 24, 'kabupaten' => 'Puncak Jaya', 'tipe' => 'Kabupaten', 'kode_pos' => '98979'],
            ['id' => 375, 'provinsi_id' => 10, 'kabupaten' => 'Purbalingga', 'tipe' => 'Kabupaten', 'kode_pos' => '53312'],
            ['id' => 376, 'provinsi_id' => 9, 'kabupaten' => 'Purwakarta', 'tipe' => 'Kabupaten', 'kode_pos' => '41119'],
            ['id' => 377, 'provinsi_id' => 10, 'kabupaten' => 'Purworejo', 'tipe' => 'Kabupaten', 'kode_pos' => '54111'],
            ['id' => 378, 'provinsi_id' => 25, 'kabupaten' => 'Raja Ampat', 'tipe' => 'Kabupaten', 'kode_pos' => '98489'],
            ['id' => 379, 'provinsi_id' => 4, 'kabupaten' => 'Rejang Lebong', 'tipe' => 'Kabupaten', 'kode_pos' => '39112'],
            ['id' => 380, 'provinsi_id' => 10, 'kabupaten' => 'Rembang', 'tipe' => 'Kabupaten', 'kode_pos' => '59219'],
            ['id' => 381, 'provinsi_id' => 26, 'kabupaten' => 'Rokan Hilir', 'tipe' => 'Kabupaten', 'kode_pos' => '28992'],
            ['id' => 382, 'provinsi_id' => 26, 'kabupaten' => 'Rokan Hulu', 'tipe' => 'Kabupaten', 'kode_pos' => '28511'],
            ['id' => 383, 'provinsi_id' => 23, 'kabupaten' => 'Rote Ndao', 'tipe' => 'Kabupaten', 'kode_pos' => '85982'],
            ['id' => 384, 'provinsi_id' => 21, 'kabupaten' => 'Sabang', 'tipe' => 'Kota', 'kode_pos' => '23512'],
            ['id' => 385, 'provinsi_id' => 23, 'kabupaten' => 'Sabu Raijua', 'tipe' => 'Kabupaten', 'kode_pos' => '85391'],
            ['id' => 386, 'provinsi_id' => 10, 'kabupaten' => 'Salatiga', 'tipe' => 'Kota', 'kode_pos' => '50711'],
            ['id' => 387, 'provinsi_id' => 15, 'kabupaten' => 'Samarinda', 'tipe' => 'Kota', 'kode_pos' => '75133'],
            ['id' => 388, 'provinsi_id' => 12, 'kabupaten' => 'Sambas', 'tipe' => 'Kabupaten', 'kode_pos' => '79453'],
            ['id' => 389, 'provinsi_id' => 34, 'kabupaten' => 'Samosir', 'tipe' => 'Kabupaten', 'kode_pos' => '22392'],
            ['id' => 390, 'provinsi_id' => 11, 'kabupaten' => 'Sampang', 'tipe' => 'Kabupaten', 'kode_pos' => '69219'],
            ['id' => 391, 'provinsi_id' => 12, 'kabupaten' => 'Sanggau', 'tipe' => 'Kabupaten', 'kode_pos' => '78557'],
            ['id' => 392, 'provinsi_id' => 24, 'kabupaten' => 'Sarmi', 'tipe' => 'Kabupaten', 'kode_pos' => '99373'],
            ['id' => 393, 'provinsi_id' => 8, 'kabupaten' => 'Sarolangun', 'tipe' => 'Kabupaten', 'kode_pos' => '37419'],
            ['id' => 394, 'provinsi_id' => 32, 'kabupaten' => 'Sawah Lunto', 'tipe' => 'Kota', 'kode_pos' => '27416'],
            ['id' => 395, 'provinsi_id' => 12, 'kabupaten' => 'Sekadau', 'tipe' => 'Kabupaten', 'kode_pos' => '79583'],
            ['id' => 396, 'provinsi_id' => 28, 'kabupaten' => 'Selayar (Kepulauan Selayar)', 'tipe' => 'Kabupaten', 'kode_pos' => '92812'],
            ['id' => 397, 'provinsi_id' => 4, 'kabupaten' => 'Seluma', 'tipe' => 'Kabupaten', 'kode_pos' => '38811'],
            ['id' => 398, 'provinsi_id' => 10, 'kabupaten' => 'Semarang', 'tipe' => 'Kabupaten', 'kode_pos' => '50511'],
            ['id' => 399, 'provinsi_id' => 10, 'kabupaten' => 'Semarang', 'tipe' => 'Kota', 'kode_pos' => '50135'],
            ['id' => 400, 'provinsi_id' => 19, 'kabupaten' => 'Seram Bagian Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '97561'],
            ['id' => 401, 'provinsi_id' => 19, 'kabupaten' => 'Seram Bagian Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '97581'],
            ['id' => 402, 'provinsi_id' => 3, 'kabupaten' => 'Serang', 'tipe' => 'Kabupaten', 'kode_pos' => '42182'],
            ['id' => 403, 'provinsi_id' => 3, 'kabupaten' => 'Serang', 'tipe' => 'Kota', 'kode_pos' => '42111'],
            ['id' => 404, 'provinsi_id' => 34, 'kabupaten' => 'Serdang Bedagai', 'tipe' => 'Kabupaten', 'kode_pos' => '20915'],
            ['id' => 405, 'provinsi_id' => 14, 'kabupaten' => 'Seruyan', 'tipe' => 'Kabupaten', 'kode_pos' => '74211'],
            ['id' => 406, 'provinsi_id' => 26, 'kabupaten' => 'Siak', 'tipe' => 'Kabupaten', 'kode_pos' => '28623'],
            ['id' => 407, 'provinsi_id' => 34, 'kabupaten' => 'Sibolga', 'tipe' => 'Kota', 'kode_pos' => '22522'],
            ['id' => 408, 'provinsi_id' => 28, 'kabupaten' => 'Sidenreng Rappang/Rapang', 'tipe' => 'Kabupaten', 'kode_pos' => '91613'],
            ['id' => 409, 'provinsi_id' => 11, 'kabupaten' => 'Sidoarjo', 'tipe' => 'Kabupaten', 'kode_pos' => '61219'],
            ['id' => 410, 'provinsi_id' => 29, 'kabupaten' => 'Sigi', 'tipe' => 'Kabupaten', 'kode_pos' => '94364'],
            ['id' => 411, 'provinsi_id' => 32, 'kabupaten' => 'Sijunjung (Sawah Lunto Sijunjung)', 'tipe' => 'Kabupaten', 'kode_pos' => '27511'],
            ['id' => 412, 'provinsi_id' => 23, 'kabupaten' => 'Sikka', 'tipe' => 'Kabupaten', 'kode_pos' => '86121'],
            ['id' => 413, 'provinsi_id' => 34, 'kabupaten' => 'Simalungun', 'tipe' => 'Kabupaten', 'kode_pos' => '21162'],
            ['id' => 414, 'provinsi_id' => 21, 'kabupaten' => 'Simeulue', 'tipe' => 'Kabupaten', 'kode_pos' => '23891'],
            ['id' => 415, 'provinsi_id' => 12, 'kabupaten' => 'Singkawang', 'tipe' => 'Kota', 'kode_pos' => '79117'],
            ['id' => 416, 'provinsi_id' => 28, 'kabupaten' => 'Sinjai', 'tipe' => 'Kabupaten', 'kode_pos' => '92615'],
            ['id' => 417, 'provinsi_id' => 12, 'kabupaten' => 'Sintang', 'tipe' => 'Kabupaten', 'kode_pos' => '78619'],
            ['id' => 418, 'provinsi_id' => 11, 'kabupaten' => 'Situbondo', 'tipe' => 'Kabupaten', 'kode_pos' => '68316'],
            ['id' => 419, 'provinsi_id' => 5, 'kabupaten' => 'Sleman', 'tipe' => 'Kabupaten', 'kode_pos' => '55513'],
            ['id' => 420, 'provinsi_id' => 32, 'kabupaten' => 'Solok', 'tipe' => 'Kabupaten', 'kode_pos' => '27365'],
            ['id' => 421, 'provinsi_id' => 32, 'kabupaten' => 'Solok', 'tipe' => 'Kota', 'kode_pos' => '27315'],
            ['id' => 422, 'provinsi_id' => 32, 'kabupaten' => 'Solok Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '27779'],
            ['id' => 423, 'provinsi_id' => 28, 'kabupaten' => 'Soppeng', 'tipe' => 'Kabupaten', 'kode_pos' => '90812'],
            ['id' => 424, 'provinsi_id' => 25, 'kabupaten' => 'Sorong', 'tipe' => 'Kabupaten', 'kode_pos' => '98431'],
            ['id' => 425, 'provinsi_id' => 25, 'kabupaten' => 'Sorong', 'tipe' => 'Kota', 'kode_pos' => '98411'],
            ['id' => 426, 'provinsi_id' => 25, 'kabupaten' => 'Sorong Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '98454'],
            ['id' => 427, 'provinsi_id' => 10, 'kabupaten' => 'Sragen', 'tipe' => 'Kabupaten', 'kode_pos' => '57211'],
            ['id' => 428, 'provinsi_id' => 9, 'kabupaten' => 'Subang', 'tipe' => 'Kabupaten', 'kode_pos' => '41215'],
            ['id' => 429, 'provinsi_id' => 21, 'kabupaten' => 'Subulussalam', 'tipe' => 'Kota', 'kode_pos' => '24882'],
            ['id' => 430, 'provinsi_id' => 9, 'kabupaten' => 'Sukabumi', 'tipe' => 'Kabupaten', 'kode_pos' => '43311'],
            ['id' => 431, 'provinsi_id' => 9, 'kabupaten' => 'Sukabumi', 'tipe' => 'Kota', 'kode_pos' => '43114'],
            ['id' => 432, 'provinsi_id' => 14, 'kabupaten' => 'Sukamara', 'tipe' => 'Kabupaten', 'kode_pos' => '74712'],
            ['id' => 433, 'provinsi_id' => 10, 'kabupaten' => 'Sukoharjo', 'tipe' => 'Kabupaten', 'kode_pos' => '57514'],
            ['id' => 434, 'provinsi_id' => 23, 'kabupaten' => 'Sumba Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '87219'],
            ['id' => 435, 'provinsi_id' => 23, 'kabupaten' => 'Sumba Barat Daya', 'tipe' => 'Kabupaten', 'kode_pos' => '87453'],
            ['id' => 436, 'provinsi_id' => 23, 'kabupaten' => 'Sumba Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '87358'],
            ['id' => 437, 'provinsi_id' => 23, 'kabupaten' => 'Sumba Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '87112'],
            ['id' => 438, 'provinsi_id' => 22, 'kabupaten' => 'Sumbawa', 'tipe' => 'Kabupaten', 'kode_pos' => '84315'],
            ['id' => 439, 'provinsi_id' => 22, 'kabupaten' => 'Sumbawa Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '84419'],
            ['id' => 440, 'provinsi_id' => 9, 'kabupaten' => 'Sumedang', 'tipe' => 'Kabupaten', 'kode_pos' => '45326'],
            ['id' => 441, 'provinsi_id' => 11, 'kabupaten' => 'Sumenep', 'tipe' => 'Kabupaten', 'kode_pos' => '69413'],
            ['id' => 442, 'provinsi_id' => 8, 'kabupaten' => 'Sungaipenuh', 'tipe' => 'Kota', 'kode_pos' => '37113'],
            ['id' => 443, 'provinsi_id' => 24, 'kabupaten' => 'Supiori', 'tipe' => 'Kabupaten', 'kode_pos' => '98164'],
            ['id' => 444, 'provinsi_id' => 11, 'kabupaten' => 'Surabaya', 'tipe' => 'Kota', 'kode_pos' => '60119'],
            ['id' => 445, 'provinsi_id' => 10, 'kabupaten' => 'Surakarta (Solo)', 'tipe' => 'Kota', 'kode_pos' => '57113'],
            ['id' => 446, 'provinsi_id' => 13, 'kabupaten' => 'Tabalong', 'tipe' => 'Kabupaten', 'kode_pos' => '71513'],
            ['id' => 447, 'provinsi_id' => 1, 'kabupaten' => 'Tabanan', 'tipe' => 'Kabupaten', 'kode_pos' => '82119'],
            ['id' => 448, 'provinsi_id' => 28, 'kabupaten' => 'Takalar', 'tipe' => 'Kabupaten', 'kode_pos' => '92212'],
            ['id' => 449, 'provinsi_id' => 25, 'kabupaten' => 'Tambrauw', 'tipe' => 'Kabupaten', 'kode_pos' => '98475'],
            ['id' => 450, 'provinsi_id' => 16, 'kabupaten' => 'Tana Tidung', 'tipe' => 'Kabupaten', 'kode_pos' => '77611'],
            ['id' => 451, 'provinsi_id' => 28, 'kabupaten' => 'Tana Toraja', 'tipe' => 'Kabupaten', 'kode_pos' => '91819'],
            ['id' => 452, 'provinsi_id' => 13, 'kabupaten' => 'Tanah Bumbu', 'tipe' => 'Kabupaten', 'kode_pos' => '72211'],
            ['id' => 453, 'provinsi_id' => 32, 'kabupaten' => 'Tanah Datar', 'tipe' => 'Kabupaten', 'kode_pos' => '27211'],
            ['id' => 454, 'provinsi_id' => 13, 'kabupaten' => 'Tanah Laut', 'tipe' => 'Kabupaten', 'kode_pos' => '70811'],
            ['id' => 455, 'provinsi_id' => 3, 'kabupaten' => 'Tangerang', 'tipe' => 'Kabupaten', 'kode_pos' => '15914'],
            ['id' => 456, 'provinsi_id' => 3, 'kabupaten' => 'Tangerang', 'tipe' => 'Kota', 'kode_pos' => '15111'],
            ['id' => 457, 'provinsi_id' => 3, 'kabupaten' => 'Tangerang Selatan', 'tipe' => 'Kota', 'kode_pos' => '15332'],
            ['id' => 458, 'provinsi_id' => 18, 'kabupaten' => 'Tanggamus', 'tipe' => 'Kabupaten', 'kode_pos' => '35619'],
            ['id' => 459, 'provinsi_id' => 34, 'kabupaten' => 'Tanjung Balai', 'tipe' => 'Kota', 'kode_pos' => '21321'],
            ['id' => 460, 'provinsi_id' => 8, 'kabupaten' => 'Tanjung Jabung Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '36513'],
            ['id' => 461, 'provinsi_id' => 8, 'kabupaten' => 'Tanjung Jabung Timur', 'tipe' => 'Kabupaten', 'kode_pos' => '36719'],
            ['id' => 462, 'provinsi_id' => 17, 'kabupaten' => 'Tanjung Pinang', 'tipe' => 'Kota', 'kode_pos' => '29111'],
            ['id' => 463, 'provinsi_id' => 34, 'kabupaten' => 'Tapanuli Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '22742'],
            ['id' => 464, 'provinsi_id' => 34, 'kabupaten' => 'Tapanuli Tengah', 'tipe' => 'Kabupaten', 'kode_pos' => '22611'],
            ['id' => 465, 'provinsi_id' => 34, 'kabupaten' => 'Tapanuli Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '22414'],
            ['id' => 466, 'provinsi_id' => 13, 'kabupaten' => 'Tapin', 'tipe' => 'Kabupaten', 'kode_pos' => '71119'],
            ['id' => 467, 'provinsi_id' => 16, 'kabupaten' => 'Tarakan', 'tipe' => 'Kota', 'kode_pos' => '77114'],
            ['id' => 468, 'provinsi_id' => 9, 'kabupaten' => 'Tasikmalaya', 'tipe' => 'Kabupaten', 'kode_pos' => '46411'],
            ['id' => 469, 'provinsi_id' => 9, 'kabupaten' => 'Tasikmalaya', 'tipe' => 'Kota', 'kode_pos' => '46116'],
            ['id' => 470, 'provinsi_id' => 34, 'kabupaten' => 'Tebing Tinggi', 'tipe' => 'Kota', 'kode_pos' => '20632'],
            ['id' => 471, 'provinsi_id' => 8, 'kabupaten' => 'Tebo', 'tipe' => 'Kabupaten', 'kode_pos' => '37519'],
            ['id' => 472, 'provinsi_id' => 10, 'kabupaten' => 'Tegal', 'tipe' => 'Kabupaten', 'kode_pos' => '52419'],
            ['id' => 473, 'provinsi_id' => 10, 'kabupaten' => 'Tegal', 'tipe' => 'Kota', 'kode_pos' => '52114'],
            ['id' => 474, 'provinsi_id' => 25, 'kabupaten' => 'Teluk Bintuni', 'tipe' => 'Kabupaten', 'kode_pos' => '98551'],
            ['id' => 475, 'provinsi_id' => 25, 'kabupaten' => 'Teluk Wondama', 'tipe' => 'Kabupaten', 'kode_pos' => '98591'],
            ['id' => 476, 'provinsi_id' => 10, 'kabupaten' => 'Temanggung', 'tipe' => 'Kabupaten', 'kode_pos' => '56212'],
            ['id' => 477, 'provinsi_id' => 20, 'kabupaten' => 'Ternate', 'tipe' => 'Kota', 'kode_pos' => '97714'],
            ['id' => 478, 'provinsi_id' => 20, 'kabupaten' => 'Tidore Kepulauan', 'tipe' => 'Kota', 'kode_pos' => '97815'],
            ['id' => 479, 'provinsi_id' => 23, 'kabupaten' => 'Timor Tengah Selatan', 'tipe' => 'Kabupaten', 'kode_pos' => '85562'],
            ['id' => 480, 'provinsi_id' => 23, 'kabupaten' => 'Timor Tengah Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '85612'],
            ['id' => 481, 'provinsi_id' => 34, 'kabupaten' => 'Toba Samosir', 'tipe' => 'Kabupaten', 'kode_pos' => '22316'],
            ['id' => 482, 'provinsi_id' => 29, 'kabupaten' => 'Tojo Una-Una', 'tipe' => 'Kabupaten', 'kode_pos' => '94683'],
            ['id' => 483, 'provinsi_id' => 29, 'kabupaten' => 'Toli-Toli', 'tipe' => 'Kabupaten', 'kode_pos' => '94542'],
            ['id' => 484, 'provinsi_id' => 24, 'kabupaten' => 'Tolikara', 'tipe' => 'Kabupaten', 'kode_pos' => '99411'],
            ['id' => 485, 'provinsi_id' => 31, 'kabupaten' => 'Tomohon', 'tipe' => 'Kota', 'kode_pos' => '95416'],
            ['id' => 486, 'provinsi_id' => 28, 'kabupaten' => 'Toraja Utara', 'tipe' => 'Kabupaten', 'kode_pos' => '91831'],
            ['id' => 487, 'provinsi_id' => 11, 'kabupaten' => 'Trenggalek', 'tipe' => 'Kabupaten', 'kode_pos' => '66312'],
            ['id' => 488, 'provinsi_id' => 19, 'kabupaten' => 'Tual', 'tipe' => 'Kota', 'kode_pos' => '97612'],
            ['id' => 489, 'provinsi_id' => 11, 'kabupaten' => 'Tuban', 'tipe' => 'Kabupaten', 'kode_pos' => '62319'],
            ['id' => 490, 'provinsi_id' => 18, 'kabupaten' => 'Tulang Bawang', 'tipe' => 'Kabupaten', 'kode_pos' => '34613'],
            ['id' => 491, 'provinsi_id' => 18, 'kabupaten' => 'Tulang Bawang Barat', 'tipe' => 'Kabupaten', 'kode_pos' => '34419'],
            ['id' => 492, 'provinsi_id' => 11, 'kabupaten' => 'Tulungagung', 'tipe' => 'Kabupaten', 'kode_pos' => '66212'],
            ['id' => 493, 'provinsi_id' => 28, 'kabupaten' => 'Wajo', 'tipe' => 'Kabupaten', 'kode_pos' => '90911'],
            ['id' => 494, 'provinsi_id' => 30, 'kabupaten' => 'Wakatobi', 'tipe' => 'Kabupaten', 'kode_pos' => '93791'],
            ['id' => 495, 'provinsi_id' => 24, 'kabupaten' => 'Waropen', 'tipe' => 'Kabupaten', 'kode_pos' => '98269'],
            ['id' => 496, 'provinsi_id' => 18, 'kabupaten' => 'Way Kanan', 'tipe' => 'Kabupaten', 'kode_pos' => '34711'],
            ['id' => 497, 'provinsi_id' => 10, 'kabupaten' => 'Wonogiri', 'tipe' => 'Kabupaten', 'kode_pos' => '57619'],
            ['id' => 498, 'provinsi_id' => 10, 'kabupaten' => 'Wonosobo', 'tipe' => 'Kabupaten', 'kode_pos' => '56311'],
            ['id' => 499, 'provinsi_id' => 24, 'kabupaten' => 'Yahukimo', 'tipe' => 'Kabupaten', 'kode_pos' => '99041'],
            ['id' => 500, 'provinsi_id' => 24, 'kabupaten' => 'Yalimo', 'tipe' => 'Kabupaten', 'kode_pos' => '99481'],
            ['id' => 501, 'provinsi_id' => 5, 'kabupaten' => 'Yogyakarta', 'tipe' => 'Kota', 'kode_pos' => '55222'],
        ];

        DB::table('provinsi')->insert($provinsi);
        DB::table('kabupaten')->insert($kabupaten);
    }
}
